version: '3.8'

services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/testpassword123
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_bolt_advertised__address=neo4j:7687
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_server_http_advertised__address=neo4j:7474
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474", "-O", "/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-ananke}
      - MYSQL_USER=${MYSQL_USER:-ananke}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-anankepass}
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --bind 0.0.0.0 --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 3

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    command: celery flower --broker=redis://redis:6379/0 --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "poetry install && poetry run celery -A app.tasks worker --loglevel=info"
    environment:
      - DOCKER_NETWORK=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword123
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=ananke
      - MYSQL_PASSWORD=anankepass
      - MYSQL_DATABASE=ananke
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
      - QWEN_API_KEY=sk-46e78b90eb8e4d6ebef79f265891f238
      - CHROMA_HOST=chromadb
    depends_on:
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      mysql:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "app.tasks", "inspect", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "poetry install && poetry run python tests/test_document_workflow.py"
    environment:
      - DOCKER_NETWORK=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword123
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=ananke
      - MYSQL_PASSWORD=anankepass
      - MYSQL_DATABASE=ananke
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
      - QWEN_API_KEY=sk-46e78b90eb8e4d6ebef79f265891f238
      - CHROMA_HOST=chromadb
    depends_on:
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      mysql:
        condition: service_healthy
      chromadb:
        condition: service_healthy
      celery-worker:
        condition: service_healthy

volumes:
  redis_data:
  neo4j_data:
  neo4j_logs:
  mysql_data:
  chroma_data:
